on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  cache: 0

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: cargo test && cargo build --release
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install rustfmt
      run: rustup component add rustfmt
    - name: rustfmt
      run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install clippy
      run: rustup component add clippy
    - name: clippy
      run: cargo clippy -D clippy::all
